
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: flaskapp-argocd-deployment
  name: flaskapp-argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskapp-argocd-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flaskapp-argocd-deployment
    spec:
      containers:
      - image: avindudocker1/gitops-jenkins-build:6
        name: flaskapp-argocd-deployment
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: lb-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: flaskapp-argocd-deployment
